[package]
name = "battleships"
version = "0.1.0"
authors = ["James Deery <james.deery@jadex.org>"]

[dependencies]
glium = "*"
rand = "*"
alice = { git = "https://github.com/derkyjadex/alice-rs.git" }
